// Checked-in inventory of every reader-app "chrome" string routed through
// ChromeTranslationService (impact-discipleship-library-new's
// core/services/chrome-translation.service.ts) - i.e. every static label,
// menu item, heading, button, hint, and error/dialog message outside of a
// lesson's own Form.io-rendered content, which is translated separately (see
// TranslationService/CommonTranslation's existing Form.io-schema use).
//
// This list is NOT read by the reader app at runtime - lookup there stays
// purely text-keyed against whatever `commonTranslations` docs actually
// exist in Firestore (see ChromeTranslationService), same as it already
// works for Form.io boilerplate. This catalog exists solely so the manager
// app's Common Translations screen can list "App Chrome Text" as a distinct,
// browsable group (grouped by `area`) alongside its existing lesson-derived
// phrase list, without staff having to hunt a flat alphabetical list.
//
// Keep this in sync by hand: whenever new user-facing text is added to the
// reader app outside a Form.io schema, add an entry here in the same commit
// (see CLAUDE.md). There is no automated drift-detection in v1.
//
// `text` is the exact literal string (or, for parameterized strings, the
// exact template with `{token}` placeholders left in) passed to
// `chrome.t()`/`chrome.html()` - it must match byte-for-byte, since that's
// the actual Firestore lookup key.
export interface ChromeTextCatalogEntry {
  text: string;
  kind: 'label' | 'html';
  /** Human grouping for the admin UI only, e.g. "Shell > Toolbar & Menu". */
  area: string;
}

export const CHROME_TEXT_CATALOG: ChromeTextCatalogEntry[] = [
  // --- Shell: toolbar, account menu, idle-warning dialog ---
  { text: 'Impact Discipleship Library', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: "You're offline - showing saved content", kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Offline', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Menu', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Store', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Impact Groups', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Settings', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Help', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Sign out', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Still there?', kind: 'label', area: 'Shell > Idle Warning Dialog' },
  {
    text: "You've been inactive for a while. For your security, you'll be signed out in {remaining} unless you'd like to stay signed in.",
    kind: 'label',
    area: 'Shell > Idle Warning Dialog',
  },
  { text: 'Stay signed in', kind: 'label', area: 'Shell > Idle Warning Dialog' },

  // --- Auth: Login ---
  { text: 'Impact Discipleship Library', kind: 'label', area: 'Auth > Login' },
  { text: 'You were signed out after a period of inactivity. Please sign in again.', kind: 'label', area: 'Auth > Login' },
  { text: 'Email', kind: 'label', area: 'Auth > Login' },
  { text: 'Email is required', kind: 'label', area: 'Auth > Login' },
  { text: 'Enter a valid email', kind: 'label', area: 'Auth > Login' },
  { text: 'Password', kind: 'label', area: 'Auth > Login' },
  { text: 'Password is required', kind: 'label', area: 'Auth > Login' },
  { text: 'Password must be at least 6 characters', kind: 'label', area: 'Auth > Login' },
  { text: 'Sign in', kind: 'label', area: 'Auth > Login' },
  { text: 'Forgot password?', kind: 'label', area: 'Auth > Login' },
  { text: "Don't have an account? Sign up", kind: 'label', area: 'Auth > Login' },
  { text: "Enter your email and we'll send you a link to reset your password.", kind: 'label', area: 'Auth > Login' },
  { text: 'Send reset link', kind: 'label', area: 'Auth > Login' },
  { text: 'Back to sign in', kind: 'label', area: 'Auth > Login' },
  { text: 'Invalid email or password.', kind: 'label', area: 'Auth > Login' },
  { text: 'Something went wrong. Please try again.', kind: 'label', area: 'Auth > Login' },
  { text: 'Something went wrong sending that email. Please try again.', kind: 'label', area: 'Auth > Login' },
  { text: "If an account exists for that email, we've sent a link to reset your password.", kind: 'label', area: 'Auth > Login' },

  // --- Auth: Signup ---
  { text: 'Confirm password', kind: 'label', area: 'Auth > Signup' },
  { text: 'Please confirm your password', kind: 'label', area: 'Auth > Signup' },
  { text: "Passwords don't match", kind: 'label', area: 'Auth > Signup' },
  { text: 'An account with that email already exists.', kind: 'label', area: 'Auth > Signup' },
  { text: 'Try signing in instead.', kind: 'label', area: 'Auth > Signup' },
  { text: 'Create account', kind: 'label', area: 'Auth > Signup' },
  { text: 'Already have an account? Sign in', kind: 'label', area: 'Auth > Signup' },
  { text: 'Password is too weak. Use at least 6 characters.', kind: 'label', area: 'Auth > Signup' },
  { text: 'Enter a valid email address.', kind: 'label', area: 'Auth > Signup' },

  // --- Auth: Invite landing ---
  { text: 'Invite not found', kind: 'label', area: 'Auth > Invite Landing' },
  { text: "This invite link doesn't look valid, or the group may no longer exist.", kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Go to sign in', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Invite declined', kind: 'label', area: 'Auth > Invite Landing' },
  { text: "You've declined this invite. If you change your mind, ask the group leader to send a new one.", kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Already responded', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'This invite has already been accepted.', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Different account signed in', kind: 'label', area: 'Auth > Invite Landing' },
  {
    text: "This invite was sent to {email}, but you're currently signed in as a different account. Sign out to continue with the invited email.",
    kind: 'label',
    area: 'Auth > Invite Landing',
  },
  { text: 'Sign out and continue', kind: 'label', area: 'Auth > Invite Landing' },
  { text: "You're invited to an Impact Group", kind: 'label', area: 'Auth > Invite Landing' },
  { text: '{leader} has invited you to join {group}, studying {book}.', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Online: {info}', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Details to follow', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'The group leader may also provide you a book license if one is available.', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'No thanks', kind: 'label', area: 'Auth > Invite Landing' },
  { text: "Yes, I'm interested", kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Let {leader} know why (optional)', kind: 'label', area: 'Auth > Invite Landing' },
  { text: "e.g. This day/time doesn't work for me right now", kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Declining…', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Skip and decline', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Send reason and decline', kind: 'label', area: 'Auth > Invite Landing' },
  { text: 'Something went wrong joining this group. Please try again.', kind: 'label', area: 'Auth > Invite Landing' },

  // --- Settings ---
  { text: 'Back to library', kind: 'label', area: 'Settings' },
  { text: 'Account', kind: 'label', area: 'Settings' },
  { text: 'Appearance', kind: 'label', area: 'Settings' },
  { text: 'Dark Mode', kind: 'label', area: 'Settings' },
  { text: 'Toggle dark mode', kind: 'label', area: 'Settings' },
  { text: 'Color Theme', kind: 'label', area: 'Settings' },
  { text: 'Language', kind: 'label', area: 'Settings' },
  { text: 'Preferred lesson language', kind: 'label', area: 'Settings' },
  { text: 'English', kind: 'label', area: 'Settings' },
  {
    text: 'A lesson renders in this language when a translation exists for it, and in its original language otherwise.',
    kind: 'label',
    area: 'Settings',
  },
  { text: 'Sign-in Location', kind: 'label', area: 'Settings' },
  {
    text: 'Approximate location detected from your most recent sign-in.',
    kind: 'label',
    area: 'Settings',
  },
  { text: 'Notifications', kind: 'label', area: 'Settings' },
  { text: 'Push notifications', kind: 'label', area: 'Settings' },
  { text: 'Toggle push notifications', kind: 'label', area: 'Settings' },
  {
    text: 'Get notified about group chat, direct messages, join requests, shared prayer requests, and announcements from the library team.',
    kind: 'label',
    area: 'Settings',
  },
  { text: 'Enable browser notifications', kind: 'label', area: 'Settings' },

  // --- Messages (admin-announcement inbox) ---
  { text: 'Messages', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'Messages', kind: 'label', area: 'Messages' },
  { text: 'No messages yet.', kind: 'label', area: 'Messages' },
  {
    text: 'Turn on notifications to hear about new messages right away.',
    kind: 'label',
    area: 'Messages',
  },
  { text: 'New', kind: 'label', area: 'Messages' },
  { text: 'Delete message', kind: 'label', area: 'Messages' },
  { text: 'Delete this message?', kind: 'label', area: 'Messages' },
  {
    text: "It will be removed from your inbox and can't be brought back.",
    kind: 'label',
    area: 'Messages',
  },
  { text: 'Delete', kind: 'label', area: 'Messages' },
  { text: 'Could not delete the message. Please try again.', kind: 'label', area: 'Messages' },

  // --- Books list / Book detail (title text itself is covered separately via TitleTranslationService) ---
  { text: 'Books', kind: 'label', area: 'Books' },
  { text: "You don't have any books yet. Contact us to purchase access.", kind: 'label', area: 'Books' },
  { text: "You don't have access to this book. Contact us to purchase access.", kind: 'label', area: 'Books' },
  { text: 'No lessons in this unit yet.', kind: 'label', area: 'Books' },
  { text: 'No units in this book yet.', kind: 'label', area: 'Books' },

  // --- Lesson view chrome (outside the Form.io-rendered form itself) ---
  { text: "You don't have access to this lesson. Contact us to purchase access.", kind: 'label', area: 'Lesson View' },
  { text: 'Book', kind: 'label', area: 'Lesson View' },
  { text: 'Lesson', kind: 'label', area: 'Lesson View' },
  { text: 'Highlight', kind: 'label', area: 'Lesson View' },
  { text: 'Something went wrong saving your answers. Please try again.', kind: 'label', area: 'Lesson View' },
  { text: "You're offline - your answers are saved on this device and will sync automatically once you're back online.", kind: 'label', area: 'Lesson View' },

  // --- Store ---
  { text: 'Back to library', kind: 'label', area: 'Store' },
  { text: 'Store', kind: 'label', area: 'Store' },
  { text: '{n} book selected', kind: 'label', area: 'Store' },
  { text: '{n} books selected', kind: 'label', area: 'Store' },
  { text: 'The store needs an internet connection. Reconnect to browse and purchase books.', kind: 'label', area: 'Store' },
  { text: "You're all set!", kind: 'label', area: 'Store' },
  { text: 'You now have access to:', kind: 'label', area: 'Store' },
  { text: 'Buy more books', kind: 'label', area: 'Store' },
  { text: "Couldn't load the store right now. Please try again later.", kind: 'label', area: 'Store' },
  { text: 'No digital books are available right now.', kind: 'label', area: 'Store' },
  { text: 'You already have access (staff)', kind: 'label', area: 'Store' },
  { text: 'You already own this book', kind: 'label', area: 'Store' },
  { text: 'Select to purchase', kind: 'label', area: 'Store' },
  { text: 'Coupon code', kind: 'label', area: 'Store' },
  { text: 'Remove', kind: 'label', area: 'Store' },
  { text: 'Apply', kind: 'label', area: 'Store' },
  { text: '{code} applied ({percent}% off)', kind: 'label', area: 'Store' },
  { text: 'Subtotal', kind: 'label', area: 'Store' },
  { text: 'Discount', kind: 'label', area: 'Store' },
  { text: 'Total', kind: 'label', area: 'Store' },
  { text: 'Get Book', kind: 'label', area: 'Store' },
  { text: 'Get Books', kind: 'label', area: 'Store' },
  { text: "Payment isn't available right now. Please try again later.", kind: 'label', area: 'Store' },
  { text: 'Enter a coupon code.', kind: 'label', area: 'Store' },
  { text: 'That coupon code is not valid.', kind: 'label', area: 'Store' },
  { text: 'That coupon does not apply to the selected books.', kind: 'label', area: 'Store' },
  { text: 'Could not check that coupon right now. Please try again.', kind: 'label', area: 'Store' },
  {
    text: 'Your payment succeeded but we could not record your order. Please contact us with your PayPal receipt so we can unlock your books.',
    kind: 'label',
    area: 'Store',
  },
  { text: 'Something went wrong completing your purchase. Please try again.', kind: 'label', area: 'Store' },
  {
    text: 'Your purchase was recorded, but we hit a problem unlocking your books. Please contact us and we will sort it out.',
    kind: 'label',
    area: 'Store',
  },
  { text: 'There was a problem processing your PayPal payment. Please try again.', kind: 'label', area: 'Store' },
  // Fallback series-group heading (Store's collapsible product groups, and
  // My Books' grouped list) for a book/product whose seriesId doesn't
  // resolve to a known series - shared between both screens, one entry.
  { text: 'Other Books', kind: 'label', area: 'Store / My Books' },

  // --- Shared confirm dialog fallback defaults (callers supply title/message/confirmLabel themselves) ---
  { text: 'Cancel', kind: 'label', area: 'Shared > Confirm Dialog' },
  { text: 'Confirm', kind: 'label', area: 'Shared > Confirm Dialog' },

  // --- Impact Groups: groups-list ---
  { text: 'Back to library', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Impact Groups', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Menu', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'My Impact Groups', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Browse Impact Groups', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'You need to own at least one book to start an Impact Group', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Start an Impact Group', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'My License Purchases', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: "You'll need to own at least one book before you can start an Impact Group around it -", kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'visit the Store', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'to get started.', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: "You've joined {group}!", kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'the group', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: "You've also been granted a license for this book.", kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'The group leader will follow up with you about book access.', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: "You haven't joined or started any Impact Groups yet -", kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'browse to find one', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'or start your own above.', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Unknown book', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Leader', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Request Sent', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Member', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Declined', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Closed', kind: 'label', area: 'Impact Groups > Groups List' },
  { text: 'Something went wrong creating the group. Please try again.', kind: 'label', area: 'Impact Groups > Groups List' },

  // --- Impact Groups: Browse dialog ---
  { text: 'Search by name, city, or state', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Search near me', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Within', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: '{n} {unit}', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Getting your location…', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Location permission was denied - allow it in your browser to search nearby.', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: "Your browser doesn't support location search.", kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: "Couldn't get your location. Please try again.", kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'No open Impact Groups right now. Be the first to start one.', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'No Impact Groups match your search.', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Requesting…', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Join', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Max {n}', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Started by {name}', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: "You don't own this book yet", kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Could not send your request to join. Please try again.', kind: 'label', area: 'Impact Groups > Browse Dialog' },
  { text: 'Close', kind: 'label', area: 'Impact Groups > Browse Dialog' },

  // --- Impact Groups: Group Wizard (shared submodule, used by both apps via CHROME_TEXT_SERVICE) ---
  { text: 'Edit Impact Group', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Start Impact Group for Next Book', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Start an Impact Group', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Step {n} of {count}', kind: 'label', area: 'Impact Groups > Group Wizard' },
  {
    text: "Pick the next book for this group to study. Group licenses are book-specific and won't carry over - you'll need to buy or assign new licenses for this book once members join.",
    kind: 'label',
    area: 'Impact Groups > Group Wizard',
  },
  { text: 'Book', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Impact Group title', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'e.g. Tuesday Night Discussion', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Description (optional)', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Potential start date', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Time', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Time zone', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Auto-detected from your device - change it if this group meets somewhere else.', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Group size (optional)', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Leave blank for unlimited', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Not counting yourself - the group closes automatically once this many people are approved.', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Offer in-person', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Offer online', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Online details', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'e.g. Zoom link shared after signup', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Country', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'State', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'City', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Will this group meet at a public or private location (church, home, etc.)?', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Public location (e.g. a church)', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Private location (e.g. a home)', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Address', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Street address', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'OK to show this address to everyone?', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'The full address will be shown to patrons browsing Impact Groups.', kind: 'label', area: 'Impact Groups > Group Wizard' },
  {
    text: "The address stays private - only city/state will be shown to patrons. It's still used to help nearby patrons find this group.",
    kind: 'label',
    area: 'Impact Groups > Group Wizard',
  },
  { text: 'Is this Impact Group open to the public, or by invite only?', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Open to the public - anyone can find and request to join', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'By invite only - hidden from browsing and search', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Title', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Description', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Start date', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Group size', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: '{n} (plus you)', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'In-person', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Online', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Visibility', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Open to the public', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'By invite only', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Cancel', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Back', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Next', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Save Changes', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Create Impact Group', kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: "This group already has {n} approved member - group size can't be set below that.", kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: "This group already has {n} approved members - group size can't be set below that.", kind: 'label', area: 'Impact Groups > Group Wizard' },
  { text: 'Something went wrong. Please try again.', kind: 'label', area: 'Impact Groups > Group Wizard' },

  // --- Impact Groups: group-detail (tabs) ---
  { text: 'Back to Impact Groups', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Overview', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Members', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Chat', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Prayers', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Licenses', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Invites', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Leader', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Member', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Request Sent', kind: 'label', area: 'Impact Groups > Detail Tabs' },
  { text: 'Request Declined', kind: 'label', area: 'Impact Groups > Detail Tabs' },

  // --- Impact Groups: Overview tab ---
  { text: 'Book', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Location', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Online', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Schedule', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Visibility', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'By invite only', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Open to the public', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'About', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: "You don't own this book yet", kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Roster', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'member', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'members', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'You need to own {book} yourself before promoting - visit the Store', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Promoting…', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Promote to {book}', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Creating…', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Clone for a different book', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'You need another licensed book to start the next one', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Invite by Email', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Closing…', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Close Impact Group', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Withdrawing…', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Withdraw Request', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Leaving…', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Leave Group', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Message the leader', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Leave this Impact Group?', kind: 'label', area: 'Impact Groups > Overview Tab' },
  {
    text: "You'll lose access to its chat, prayer requests, and any license assigned to you through it.",
    kind: 'label',
    area: 'Impact Groups > Overview Tab',
  },
  { text: 'Close this Impact Group?', kind: 'label', area: 'Impact Groups > Overview Tab' },
  {
    text: 'Members will keep any license already assigned to them, but the group will no longer appear when browsing or inviting.',
    kind: 'label',
    area: 'Impact Groups > Overview Tab',
  },
  { text: 'Close Group', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Could not withdraw your request. Please try again.', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Could not leave the group. Please try again.', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Could not close the group. Please try again.', kind: 'label', area: 'Impact Groups > Overview Tab' },
  { text: 'Something went wrong creating the new group. Please try again.', kind: 'label', area: 'Impact Groups > Overview Tab' },
  {
    text: 'Your new group was created, but copying members over failed - you can invite them again manually.',
    kind: 'label',
    area: 'Impact Groups > Overview Tab',
  },

  // --- Impact Groups: Members tab ---
  { text: 'You need to be an approved member of this Impact Group to see its roster.', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Requests to join · {n}', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Message', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Reject', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'This group has reached its size limit', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Approving…', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Approve', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Members · {n}', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Impact Group leader', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Licensed', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Declined requests · {n}', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Reject this request?', kind: 'label', area: 'Impact Groups > Members Tab' },
  {
    text: "{name} will be notified their request to join wasn't approved. They can request again later.",
    kind: 'label',
    area: 'Impact Groups > Members Tab',
  },
  { text: 'Reject Request', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Could not approve this request. Please try again.', kind: 'label', area: 'Impact Groups > Members Tab' },
  { text: 'Could not decline this request. Please try again.', kind: 'label', area: 'Impact Groups > Members Tab' },

  // --- Impact Groups: Licenses tab ---
  { text: 'Unassigned reserve', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Assigned to members', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Buy Licenses', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'No members yet - once someone joins, you can assign a license here.', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Member', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Status', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Not licensed', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'This group has closed or changed books, so this license can no longer be revoked.', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Revoking…', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Revoke', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Assigning…', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Assign', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Could not assign a license. Please try again.', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Revoke this license?', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  {
    text: 'This member will lose access to the book unless they have another license for it. It returns to your unassigned reserve.',
    kind: 'label',
    area: 'Impact Groups > Licenses Tab',
  },
  { text: 'Revoke License', kind: 'label', area: 'Impact Groups > Licenses Tab' },
  { text: 'Could not revoke this license. Please try again.', kind: 'label', area: 'Impact Groups > Licenses Tab' },

  // --- Impact Groups: Invites tab ---
  { text: 'Invite by Email', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'No invites sent yet.', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'Canceling…', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'Cancel', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'Reason given', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'Cancel this invite?', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: "The invitee's link will stop working. You can invite them again later if you change your mind.", kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'Cancel Invite', kind: 'label', area: 'Impact Groups > Invites Tab' },
  { text: 'Could not cancel this invite. Please try again.', kind: 'label', area: 'Impact Groups > Invites Tab' },

  // --- Impact Groups: Prayer Requests tab ---
  { text: 'You need to be an approved member of this Impact Group to see its shared prayers.', kind: 'label', area: 'Impact Groups > Prayer Requests Tab' },
  { text: 'No prayers have been shared with this group yet.', kind: 'label', area: 'Impact Groups > Prayer Requests Tab' },
  { text: 'Remove', kind: 'label', area: 'Impact Groups > Prayer Requests Tab' },
  { text: 'Remove this prayer request?', kind: 'label', area: 'Impact Groups > Prayer Requests Tab' },
  { text: 'It will no longer be visible to the group. This cannot be undone.', kind: 'label', area: 'Impact Groups > Prayer Requests Tab' },
  { text: 'Could not remove that prayer. Please try again.', kind: 'label', area: 'Impact Groups > Prayer Requests Tab' },

  // --- Impact Groups: Chat tab + 1:1 Conversation ---
  { text: 'You need to be an approved member of this Impact Group to see its chat.', kind: 'label', area: 'Impact Groups > Chat' },
  { text: 'Message', kind: 'label', area: 'Impact Groups > Chat' },
  { text: 'Say something to the Impact Group…', kind: 'label', area: 'Impact Groups > Chat' },
  { text: 'Could not send your message. Please try again.', kind: 'label', area: 'Impact Groups > Chat' },
  { text: 'Back to Impact Groups', kind: 'label', area: 'Impact Groups > Conversation' },
  { text: 're: {title}', kind: 'label', area: 'Impact Groups > Conversation' },
  { text: "You don't have access to this conversation.", kind: 'label', area: 'Impact Groups > Conversation' },
  { text: 'No messages yet - say hello.', kind: 'label', area: 'Impact Groups > Conversation' },
  { text: 'Write a message…', kind: 'label', area: 'Impact Groups > Conversation' },
  { text: 'Impact Group leader', kind: 'label', area: 'Impact Groups > Conversation' },

  // --- Impact Groups: Buy Licenses dialog ---
  { text: 'Buy Licenses for {group}', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'Could not load pricing for this book right now. Please try again.', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  {
    text: "Buy licenses of {book} to hand out to this group's approved members. Any you don't hand out stay in your reserve for this book - usable in this or any of your other groups studying it, including ones you start later.",
    kind: 'label',
    area: 'Impact Groups > Buy Licenses Dialog',
  },
  { text: 'Quantity', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'Subtotal', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'Discount ({percent}% off)', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'Total', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'Get Licenses', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: "Payment isn't available right now. Please try again later.", kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'Close', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  {
    text: "Your payment succeeded but we could not record your licenses. Please contact us with this purchase's details so we can make it right.",
    kind: 'label',
    area: 'Impact Groups > Buy Licenses Dialog',
  },
  { text: 'Something went wrong completing this purchase. Please try again.', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },
  { text: 'There was a problem processing your PayPal payment. Please try again.', kind: 'label', area: 'Impact Groups > Buy Licenses Dialog' },

  // --- Impact Groups: Invite Member dialog ---
  { text: 'Invite Someone to {group}', kind: 'label', area: 'Impact Groups > Invite Member Dialog' },
  {
    text: "We'll email them an invite explaining the group and letting them say yes or no. If they say yes, they'll be walked through creating a free account and joined automatically.",
    kind: 'label',
    area: 'Impact Groups > Invite Member Dialog',
  },
  { text: 'Their email address', kind: 'label', area: 'Impact Groups > Invite Member Dialog' },
  { text: 'Attach a license to this invite', kind: 'label', area: 'Impact Groups > Invite Member Dialog' },
  {
    text: "You currently have {n} unassigned license for this book. If none is available by the time they accept, we'll let them know you'll follow up separately about book access.",
    kind: 'label',
    area: 'Impact Groups > Invite Member Dialog',
  },
  {
    text: "You currently have {n} unassigned licenses for this book. If none is available by the time they accept, we'll let them know you'll follow up separately about book access.",
    kind: 'label',
    area: 'Impact Groups > Invite Member Dialog',
  },
  { text: 'Cancel', kind: 'label', area: 'Impact Groups > Invite Member Dialog' },
  { text: 'Send Invite', kind: 'label', area: 'Impact Groups > Invite Member Dialog' },
  { text: 'Something went wrong sending this invite. Please try again.', kind: 'label', area: 'Impact Groups > Invite Member Dialog' },

  // --- Impact Groups: Promote Members dialog ---
  { text: "Who's coming to {book}?", kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: "You're already included as leader. Choose which approved members to bring into the new group.", kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: 'No other approved members to bring forward - just you for now.', kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: 'Licenses for {book}', kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: 'Buy licenses now for the selected members', kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: 'Let members buy their own', kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: 'Skip for now', kind: 'label', area: 'Impact Groups > Promote Members Dialog' },
  { text: 'Continue', kind: 'label', area: 'Impact Groups > Promote Members Dialog' },

  // --- Impact Groups: Share Prayer dialog ---
  { text: 'Share your prayer?', kind: 'label', area: 'Impact Groups > Share Prayer Dialog' },
  { text: 'Choose which of your Impact Groups can see this prayer.', kind: 'label', area: 'Impact Groups > Share Prayer Dialog' },
  { text: 'Not now', kind: 'label', area: 'Impact Groups > Share Prayer Dialog' },
  { text: 'Share', kind: 'label', area: 'Impact Groups > Share Prayer Dialog' },

  // --- Impact Groups: My License Purchases ---
  { text: 'Back to Impact Groups', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: 'My License Purchases', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: "You haven't bought any bulk licenses yet.", kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: '{n} license', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: '{n} licenses', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: 'Unassigned', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: 'Assigned to {email} in "{group}"', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: 'Unknown book', kind: 'label', area: 'Impact Groups > My License Purchases' },
  { text: 'Unknown group', kind: 'label', area: 'Impact Groups > My License Purchases' },

  // --- Help: shell + overview (topic labels/descriptions shared by both) ---
  { text: 'Back to library', kind: 'label', area: 'Help > Shell' },
  { text: 'Help', kind: 'label', area: 'Help > Shell' },
  { text: 'Help Topics', kind: 'label', area: 'Help > Shell' },
  { text: 'Back to Help Topics', kind: 'label', area: 'Help > Shell' },
  { text: 'Reading & Lessons', kind: 'label', area: 'Help > Topics' },
  { text: 'Impact Groups', kind: 'label', area: 'Help > Topics' },
  { text: 'Store', kind: 'label', area: 'Help > Topics' },
  { text: 'Settings & Appearance', kind: 'label', area: 'Help > Topics' },
  { text: 'Offline Support', kind: 'label', area: 'Help > Topics' },
  { text: 'Browse your books, read and answer lessons, and highlight text as you go.', kind: 'label', area: 'Help > Topics' },
  { text: 'Start or join a book discussion group - chat, messaging, and prayer sharing.', kind: 'label', area: 'Help > Topics' },
  { text: 'Buy additional book licenses with PayPal or a coupon.', kind: 'label', area: 'Help > Topics' },
  { text: 'Dark mode, color theme, preferred lesson language, and staying signed in.', kind: 'label', area: 'Help > Topics' },
  { text: 'What still works without an internet connection, and what needs one.', kind: 'label', area: 'Help > Topics' },
  {
    text: 'The Impact Discipleship Library is where you read licensed lesson content, answer and save your own responses, buy additional book licenses, and organize or join Impact Groups - patron-run book discussion groups with their own chat, messaging, and shared prayer requests. Pick a topic below to learn more.',
    kind: 'label',
    area: 'Help > Overview',
  },

  // --- Help: Reading & Lessons ---
  { text: 'From <strong>My Books</strong> (in the menu, or the book list on your Home screen), tap a <strong>Book</strong>, then a <strong>Unit</strong>, to see its lessons. Tap a lesson to open it - each one is a mix of reading content and questions to answer.', kind: 'html', area: 'Help > Reading & Lessons' },
  { text: 'On <strong>My Books</strong>, your books are grouped under their series name - handy once your library grows past a book or two.', kind: 'html', area: 'Help > Reading & Lessons' },
  { text: 'Answering and saving a lesson', kind: 'label', area: 'Help > Reading & Lessons' },
  { text: 'Fill in a lesson\'s fields, then press its <strong>Submit</strong> button (the exact label can vary lesson to lesson) to save your answers. If you\'re offline when you save, you\'ll see <em>&quot;You\'re offline - your answers are saved on this device and will sync automatically once you\'re back online.&quot;</em> - that\'s a confirmation, not an error: nothing is lost, and there\'s nothing to redo. If a save fails for any other reason, you\'ll see <em>&quot;Something went wrong saving your answers. Please try again.&quot;</em> right on the page.', kind: 'html', area: 'Help > Reading & Lessons' },
  { text: 'Reopening a lesson always reloads your last saved answers, so you can come back and pick up where you left off, or revise something you answered before - editing and re-submitting simply overwrites your previous answers for that lesson.', kind: 'label', area: 'Help > Reading & Lessons' },
  { text: 'Highlighting text', kind: 'label', area: 'Help > Reading & Lessons' },
  { text: 'Select any text in a lesson (outside of the answer fields themselves) and a small <strong>Highlight</strong> button appears right above your selection - tap it to mark that passage. To remove a highlight, tap directly on the highlighted text again; it comes right off, no confirmation needed. There\'s only one highlight style - no color choices.', kind: 'html', area: 'Help > Reading & Lessons' },
  {
    text: "Your highlights are private to you - other patrons, including anyone in an Impact Group you share with, never see them. They're tied to the lesson's current language, so a highlight made while reading in English won't appear if you later switch your preferred lesson language to a translation (see",
    kind: 'label',
    area: 'Help > Reading & Lessons',
  },
  { text: 'Settings & Appearance', kind: 'label', area: 'Help > Reading & Lessons' },
  { text: '), and vice versa.', kind: 'label', area: 'Help > Reading & Lessons' },

  // --- Help: Store ---
  { text: 'Buy additional book licenses individually from the <strong>Store</strong>, linked from the hamburger menu. Every book you don\'t already own is listed with a <strong>Select to purchase</strong> checkbox; a sticky header keeps a running total as you check books on and off. A book you already own shows a &quot;You already own this book&quot; badge instead of a checkbox.', kind: 'html', area: 'Help > Store' },
  { text: 'Purchasable books are grouped into collapsible sections by series - tap a series heading to expand or collapse it. Every series starts expanded; a book that doesn\'t belong to any series lists under an &quot;Other Books&quot; heading at the end.', kind: 'html', area: 'Help > Store' },
  { text: 'Store screen', kind: 'label', area: 'Help > Store' },
  { text: 'The Store: price, running total, and ownership status per book.', kind: 'label', area: 'Help > Store' },
  { text: 'Enter a <strong>Coupon code</strong> (appears once you\'ve selected at least one book) and click <strong>Apply</strong> for a percent-off discount - if you then uncheck the one book it applied to, the coupon is automatically removed rather than left dangling.', kind: 'html', area: 'Help > Store' },
  { text: 'If a coupon brings your total to exactly <strong>$0.00</strong>, click <strong>Get Book(s)</strong> and you\'re done - no payment is collected at all.', kind: 'html', area: 'Help > Store' },
  { text: 'Otherwise, pay with the <strong>PayPal</strong> button - this app only supports PayPal (PayPal\'s own flow lets you pay by card without an account, if you don\'t have one).', kind: 'html', area: 'Help > Store' },
  {
    text: "Access unlocks automatically the moment your purchase completes - the confirmation screen links straight into each book you just bought, and you can start reading right away with no extra step. The Store needs an internet connection; it's unavailable while you're offline.",
    kind: 'label',
    area: 'Help > Store',
  },
  {
    text: "If PayPal charges you but the app shows an error recording or unlocking your purchase, hold onto your PayPal receipt/confirmation email and contact support with it - that's exactly the situation it's for.",
    kind: 'label',
    area: 'Help > Store',
  },

  // --- Help: Settings & Appearance ---
  { text: 'Reached from the hamburger menu (top right) - that same menu also shows your name and email at the top, above Home/My Books/Store/Impact Groups/Messages/Settings/Help and Sign out. Every change on this page applies and saves immediately - there\'s no Save button, and your choices sync to your account, so they follow you to any device you sign in on.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: '<strong>Dark Mode</strong> and <strong>Color Theme</strong> - light mode and dark mode each remember their own separate color theme, so switching one doesn\'t lose the other\'s choice.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: '<strong>Preferred lesson language</strong> - a lesson renders in this language when a translation exists for it, and in its original language otherwise. Choose &quot;English&quot; to always see lessons exactly as authored.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: '<strong>Push notifications</strong> - your device gets a notification for Impact Group activity (chat messages, direct messages to you, join requests and their approval, shared prayer requests) and for announcements from the library team. On the Android app, Android asks for notification permission the first time you sign in; in a web browser, use the Enable browser notifications button. This switch silences notifications for your whole account without touching either permission.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: 'The <strong>Messages</strong> item in the hamburger menu is your inbox for announcements from the library team. A badge on the menu icon shows how many messages you have not read yet.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: 'Tap a message to read it - that clears its <strong>New</strong> flag and the badge count. Once read, a message can be deleted with its trash icon; unread messages cannot be deleted, so nothing can be dismissed unseen.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: 'Announcements also arrive as device notifications - automatically on the Android app, and in a web browser after you click <strong>Enable browser notifications</strong> (offered on the Messages screen and under Settings). Tapping a notification opens your inbox.', kind: 'html', area: 'Help > Settings & Appearance' },
  { text: 'Settings screen', kind: 'label', area: 'Help > Settings & Appearance' },
  { text: 'Settings: account email and sign-in location, appearance, preferred lesson language, and push notifications.', kind: 'label', area: 'Help > Settings & Appearance' },
  { text: 'Staying signed in', kind: 'label', area: 'Help > Settings & Appearance' },
  { text: 'For your security, you\'re automatically signed out after an hour of no activity anywhere in the app. Five minutes before that happens, a <strong>&quot;Still there?&quot;</strong> dialog warns you and offers a <strong>Stay signed in</strong> button - if you don\'t respond, you\'ll be signed out and returned to the login screen.', kind: 'html', area: 'Help > Settings & Appearance' },

  // --- Help: Offline Support ---
  {
    text: "The library is built to keep working without an internet connection. After you sign in while online, the app quietly saves a copy of every book you're licensed for - units, lessons, and images - in the background, so they're ready to read even if you lose connectivity later. This happens automatically; there's nothing to turn on.",
    kind: 'label',
    area: 'Help > Offline Support',
  },
  { text: 'What still works offline', kind: 'label', area: 'Help > Offline Support' },
  { text: 'Browsing your books and reading lessons you (or the app, in the background) have already opened while online.', kind: 'label', area: 'Help > Offline Support' },
  { text: "Answering and saving lesson questions - your answers are written locally and sync once you're back online.", kind: 'label', area: 'Help > Offline Support' },
  { text: 'Highlighting text.', kind: 'label', area: 'Help > Offline Support' },
  { text: 'What needs a connection', kind: 'label', area: 'Help > Offline Support' },
  { text: 'The <strong>Store</strong> - buying a book requires PayPal, so the whole Store page shows a &quot;needs an internet connection&quot; notice while you\'re offline instead of its usual product list.', kind: 'html', area: 'Help > Offline Support' },
  { text: '<strong>Impact Groups</strong> - browsing, joining, chat, messaging, and prayer sharing all need a live connection to Firestore.', kind: 'html', area: 'Help > Offline Support' },
  { text: 'While you\'re offline, an <strong>Offline</strong> chip appears in the toolbar, and the Store and Impact Groups links are hidden from the menu entirely rather than just disabled.', kind: 'html', area: 'Help > Offline Support' },
  { text: 'Saving a lesson while offline shows &quot;You\'re offline - your answers are saved on this device and will sync automatically once you\'re back online.&quot; - a confirmation, not an error; your answers upload on their own when connectivity returns. The &quot;Something went wrong saving your answers&quot; message now only appears when a save fails for some other reason - if you see it, trying again is the right first step.', kind: 'html', area: 'Help > Offline Support' },

  // --- Help: Impact Groups (large prose section) ---
  { text: 'Impact Groups are patron-organized book discussion groups, in-person and/or online. Open the hamburger menu (top right) and choose <strong>Impact Groups</strong> - it opens straight to <strong>My Impact Groups</strong>, the list of every group you\'ve started or requested to join. A <strong>Menu</strong> button at the top of that page also gets you to <strong>Browse Impact Groups</strong>, <strong>Start an Impact Group</strong>, and <strong>My License Purchases</strong>.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'My Impact Groups', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Each group shows as a card with its book and a status: <strong>Leader</strong> (you created it), <strong>Member</strong> (you\'re an approved member), <strong>Request Sent</strong> (still waiting on approval), or <strong>Declined</strong>. Tap a card to open that group\'s page. If you haven\'t joined or started anything yet, this page just offers to help you browse or start one.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Finding and joining a group', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Choose <strong>Browse Impact Groups</strong> from the Menu to search every open group. The search box matches a group\'s name, city, or state as you type. Toggle <strong>Search near me</strong> to also filter by distance - your browser will ask permission to share your location, then a dropdown lets you pick a radius. Only in-person groups that successfully resolved a location participate in distance search; online-only groups and closed or by-invite-only groups never show up in Browse or search at all.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Browse Impact Groups dialog', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Browse Impact Groups: search, &quot;Search near me,&quot; and every open group with a Join button.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Click <strong>Join</strong> on any open group to send a request. It shows as <strong>Request Sent</strong> until the group\'s creator approves or declines it - you can withdraw a still-pending request at any time from the group\'s own page. Once approved, the group appears under <strong>My Impact Groups</strong> with access to its tabs below.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Browse Impact Groups, filtered search results', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Typing narrows the list immediately - here, searching &quot;night&quot; matches a group by name.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Starting a group', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Choose <strong>Start an Impact Group</strong> from the Menu to open a step-by-step wizard (this is disabled, with an explanation, until you own at least one book). Whoever starts a group is its <strong>creator</strong> - there\'s no separate &quot;leader&quot; role beyond that; the creator is automatically an approved member and is the only one who can manage the group afterward.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Start an Impact Group wizard, first step', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Step 1, Basics: book, title, description, and a potential start date/time.', kind: 'label', area: 'Help > Impact Groups' },
  { text: '<strong>Basics</strong> - pick a book, give the group a title, an optional description, an optional group size limit (the group closes automatically once that many people are approved), and a potential start date and time (with a time zone, auto-detected but editable).', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Format</strong> - check <strong>Offer in-person</strong>, <strong>Offer online</strong>, or both. Choosing online asks for details (e.g. a video-call link to share once people join).', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Location</strong> <em>(in-person groups only)</em> - country, state, and city.', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Venue</strong> <em>(in-person groups only)</em> - whether you\'ll meet at a <strong>public</strong> location (like a church) or a <strong>private</strong> one (like a home), plus the address. A private address is hidden from other patrons by default - a toggle lets you opt in to showing it. It\'s still used behind the scenes so your group can be found in a nearby search either way, just never displayed unless you turn that on.', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Visibility</strong> - open to the public (anyone can find and request to join) or by invite only (hidden from Browse and search entirely - see &quot;Inviting people directly,&quot; below).', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Review</strong> - a summary of everything above, then <strong>Create Impact Group</strong>.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Impact Group wizard location step', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'The Location step, shown only when &quot;Offer in-person&quot; is checked.', kind: 'html', area: 'Help > Impact Groups' },
  { text: "A group's page", kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Opening a group takes you to its own page with a row of tabs: <strong>Overview</strong>, <strong>Members</strong>, <strong>Chat</strong>, and <strong>Prayers</strong> for everyone in the group, plus <strong>Licenses</strong> - and, for by-invite-only groups, <strong>Invites</strong> - for the creator only.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Overview: managing a group you created', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'The Overview tab summarizes the group (book, location, schedule, visibility) and, for the creator, is where every management action lives:', kind: 'label', area: 'Help > Impact Groups' },
  { text: '<strong>Promote to [next book]</strong> - shown when the group\'s book is part of a series and you already own the next one. Walks you through starting a new group for that next book, pre-filled from this one, then lets you choose which approved members to bring along and whether to buy them licenses right away or let them buy their own.', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Clone for a different book</strong> - always available as a manual alternative (needed for standalone books, or to pick something outside the series). Starts a new group pre-filled from this one for any book you own, and automatically brings your entire current roster along - no member picker, no license-buying step.', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Invite by Email</strong> - by-invite-only groups only; see &quot;Inviting people directly,&quot; below.', kind: 'html', area: 'Help > Impact Groups' },
  { text: '<strong>Close Impact Group</strong> - hides it from Browse without deleting anything; there\'s still no way to delete a group you created from this app.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'If you\'re a member rather than the creator, Overview instead offers <strong>Withdraw Request</strong> (while pending) or <strong>Leave Group</strong> (once approved) - see &quot;Leaving or closing a group,&quot; below - plus a <strong>Message the leader</strong> link once the creator has started a 1:1 conversation with you (see Messaging, below).', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Members: requests and roster', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'The Members tab lists <strong>Requests to join</strong> (creator only), the approved <strong>Members</strong> roster (creator listed first, as &quot;Impact Group leader&quot;), and any <strong>Declined requests</strong> (creator only). As creator you can <strong>Approve</strong> or <strong>Reject</strong> a pending request, or <strong>Message</strong> anyone on any of the three lists - including someone you\'ve declined. Approving is blocked once the group hits its size limit, and reaching that limit closes the group automatically. There\'s no separate &quot;remove&quot; action for an already-approved member; they leave on their own from their own Overview tab.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Chat', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Every group has one shared chat that any approved member - including you, if you\'re the creator - can post to and read. It\'s a simple running conversation, visible to the whole group; there\'s no way to edit or delete a message once it\'s sent, so it\'s meant for casual back-and-forth, not anything you\'d need to take back.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Messaging (1:1)', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Separately from the shared chat, a group\'s creator can start a private, 1:1 message thread with any individual requester or member right from the Members tab - useful for following up on a join request, coordinating details, or a private conversation that doesn\'t belong in the group chat. Once the creator starts a thread with you, a <strong>Message the leader</strong> link appears on your own Overview tab so you can read and reply - but you can\'t start a new thread yourself; it\'s always the creator who initiates.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Sharing a prayer request', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Some lessons include a prayer field. When you save a lesson with something written there, and you belong to at least one open Impact Group as an approved member, a <strong>&quot;Share your prayer?&quot;</strong> dialog offers to share it - check which of your groups should see it, then <strong>Share</strong> (or <strong>Not now</strong> to skip). It only asks again if you go back and change what you wrote; saving the same lesson again with the same prayer text won\'t re-prompt you.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Shared prayers show up on the group\'s <strong>Prayers</strong> tab for every approved member to see and pray over, alongside which lesson prompted it and who shared it. You (the author) or the group\'s creator can remove a prayer request later if it\'s no longer needed.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Licenses: buying and assigning book access', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'The creator-only <strong>Licenses</strong> tab is where you buy book licenses in bulk and hand them out to your group\'s members - separate from buying a single license for yourself in the', kind: 'html', area: 'Help > Impact Groups' },
  { text: '. Click <strong>Buy Licenses</strong>, choose a quantity, and check out (or, if a discount brings the total to $0, just claim them). Licenses you don\'t hand out immediately sit in your <strong>unassigned reserve</strong> for that book - usable in this group or any other group you run for the same book, including ones you start later. From the member ledger on this tab you can then <strong>Assign</strong> a reserved license to any approved member who doesn\'t already have one, or <strong>Revoke</strong> one you\'d previously assigned (only while the group is still open and still studying the same book).', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Choose <strong>My License Purchases</strong> from the Menu to see every bulk license purchase you\'ve made across all your groups. Each purchase lists how many licenses it bought, how many are still sitting in your unassigned reserve versus already handed out, and which member (and which group) each assigned license currently belongs to.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Inviting people directly', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'For a by-invite-only group, the creator gets an extra <strong>Invites</strong> tab. Click <strong>Invite by Email</strong>, enter the person\'s email, and optionally attach one of your unassigned licenses for that book. They\'ll get an email explaining the group with <strong>Yes, I\'m interested</strong> / <strong>No thanks</strong> buttons - accepting walks them through creating a free account (or signing in, if they already have one) and joins them automatically; declining lets them leave you an optional note explaining why, which shows up right on your Invites tab next to that invite. A still-pending invite can be <strong>Cancel</strong>ed at any time.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Leaving or closing a group', kind: 'label', area: 'Help > Impact Groups' },
  { text: 'Leaving a group (or withdrawing a still-pending request) is instant, from that group\'s own Overview tab. If you were currently holding a license the group\'s creator had assigned to you, leaving automatically frees it back into their reserve for that book rather than leaving it stuck with you. Closing a group (creator only) just hides it from Browse - it isn\'t deleted, and its chat, prayers, and history stay intact for anyone who still has the link.', kind: 'html', area: 'Help > Impact Groups' },
  { text: 'Chat messages, 1:1 messages, and shared prayer requests are only ever visible to approved members of that specific group - never to the public, and never to members of a different group you also belong to.', kind: 'label', area: 'Help > Impact Groups' },

  // --- Shell: Home / My Books menu items (added with the Dashboard) ---
  { text: 'Home', kind: 'label', area: 'Shell > Toolbar & Menu' },
  { text: 'My Books', kind: 'label', area: 'Shell > Toolbar & Menu' },

  // --- Dashboard (post-login landing screen) ---
  { text: 'Good morning', kind: 'label', area: 'Dashboard > Greeting' },
  { text: 'Good afternoon', kind: 'label', area: 'Dashboard > Greeting' },
  { text: 'Good evening', kind: 'label', area: 'Dashboard > Greeting' },
  { text: 'lessons this week', kind: 'label', area: 'Dashboard > Stats' },
  { text: 'day streak', kind: 'label', area: 'Dashboard > Stats' },
  { text: 'library complete', kind: 'label', area: 'Dashboard > Stats' },
  { text: 'Your highlight from {lesson}', kind: 'label', area: 'Dashboard > Devotional' },
  { text: 'One of your highlights', kind: 'label', area: 'Dashboard > Devotional' },
  { text: 'Revisit lesson', kind: 'label', area: 'Dashboard > Devotional' },
  { text: 'Your word is a lamp to my feet, and a light for my path.', kind: 'label', area: 'Dashboard > Devotional' },
  { text: 'I can do all things through Christ, who strengthens me.', kind: 'label', area: 'Dashboard > Devotional' },
  { text: 'Trust in the LORD with all your heart, and don’t lean on your own understanding.', kind: 'label', area: 'Dashboard > Devotional' },
  { text: 'Continue reading', kind: 'label', area: 'Dashboard > Continue Reading' },
  { text: 'Start reading', kind: 'label', area: 'Dashboard > Continue Reading' },
  { text: '{done} of {total} lessons', kind: 'label', area: 'Dashboard > Continue Reading' },
  { text: 'Resume', kind: 'label', area: 'Dashboard > Continue Reading' },
  { text: 'Start', kind: 'label', area: 'Dashboard > Continue Reading' },
  { text: "You've completed every lesson in your library - well done!", kind: 'label', area: 'Dashboard > Continue Reading' },
  { text: '{n} unread', kind: 'label', area: 'Dashboard > Alerts' },
  { text: 'No new messages', kind: 'label', area: 'Dashboard > Alerts' },
  { text: 'Join requests', kind: 'label', area: 'Dashboard > Alerts' },
  { text: '{n} waiting for your approval', kind: 'label', area: 'Dashboard > Alerts' },
  { text: 'Completed', kind: 'label', area: 'Dashboard > My Books' },
  { text: 'My Groups', kind: 'label', area: 'Dashboard > My Groups' },
  { text: 'Find or start a discussion group', kind: 'label', area: 'Dashboard > My Groups' },
  { text: '{n} pending', kind: 'label', area: 'Dashboard > My Groups' },
  { text: '{n} shared in your groups', kind: 'label', area: 'Dashboard > My Groups' },
  { text: 'Explore the store', kind: 'label', area: 'Dashboard > Store Teaser' },
  { text: '{n} more titles available', kind: 'label', area: 'Dashboard > Store Teaser' },

  // --- Help: Home Dashboard topic (nav/card + section page) ---
  { text: 'Home Dashboard', kind: 'label', area: 'Help > Topics' },
  { text: 'Your landing screen - study stats, continue reading, and what needs your attention.', kind: 'label', area: 'Help > Topics' },
  { text: 'The <strong>Home</strong> screen is the first thing you see after signing in. It gathers your study progress, a verse worth revisiting, and anything waiting on you - and every card and row on it is a shortcut into the right screen. You can always come back to it from <strong>Home</strong> in the menu.', kind: 'html', area: 'Help > Home Dashboard' },
  { text: 'Your progress at a glance', kind: 'label', area: 'Help > Home Dashboard' },
  { text: "<strong>Lessons this week</strong> counts the lessons you've submitted in the last 7 days.", kind: 'html', area: 'Help > Home Dashboard' },
  { text: "<strong>Day streak</strong> is how many days in a row you've submitted at least one lesson. It counts through yesterday, so it isn't broken before you've had a chance to study today.", kind: 'html', area: 'Help > Home Dashboard' },
  { text: '<strong>Library complete</strong> is your overall progress across every book you have access to.', kind: 'html', area: 'Help > Home Dashboard' },
  { text: 'A verse to revisit', kind: 'label', area: 'Help > Home Dashboard' },
  { text: "The colored card shows one of your own recent highlights, chosen fresh on each visit, with a Revisit lesson link back to the lesson where you marked it. If you haven't highlighted anything yet, an encouraging verse appears there instead - see", kind: 'label', area: 'Help > Home Dashboard' },
  { text: 'for how highlighting works.', kind: 'label', area: 'Help > Home Dashboard' },
  { text: '<strong>Continue reading</strong> always points at the next unfinished lesson in the book you most recently worked in - <strong>Resume</strong> takes you straight into it. A brand-new account sees <strong>Start reading</strong> for its first book instead, and once every lesson in your library is done, the card congratulates you.', kind: 'html', area: 'Help > Home Dashboard' },
  { text: 'What needs your attention', kind: 'label', area: 'Help > Home Dashboard' },
  { text: 'A <strong>Messages</strong> card shows how many unread announcements are in your inbox - the same inbox as <strong>Messages</strong> in the menu. If you lead an Impact Group and people are waiting to join, a <strong>Join requests</strong> card appears beside it; tap it to go approve or decline them.', kind: 'html', area: 'Help > Home Dashboard' },
  { text: 'Your books and groups', kind: 'label', area: 'Help > Home Dashboard' },
  { text: '<strong>My Books</strong> lists every book you have access to, each with a progress bar - tap one to open it. The same book list is also at <strong>My Books</strong> in the menu.', kind: 'html', area: 'Help > Home Dashboard' },
  { text: "<strong>My Groups</strong> lists the Impact Groups you belong to with each group's next meeting date, plus a <strong>Prayers</strong> row totaling the prayer requests shared across your groups.", kind: 'html', area: 'Help > Home Dashboard' },
  { text: "An <strong>Explore the store</strong> row appears at the bottom when there are titles you don't own yet.", kind: 'html', area: 'Help > Home Dashboard' },
  { text: "Everything above the groups section works offline from your saved content. The groups and store rows need a connection, so they simply hide while you're offline - they come back on their own when connectivity returns.", kind: 'label', area: 'Help > Home Dashboard' },

  // --- Store: Free eBooks section + in-app PDF viewer ---
  { text: 'Free eBooks', kind: 'label', area: 'Store > Free eBooks' },
  { text: 'Free PDF resources you can read right now - no purchase needed.', kind: 'label', area: 'Store > Free eBooks' },
  { text: 'Read', kind: 'label', area: 'Store > Free eBooks' },
  { text: 'Open in new tab', kind: 'label', area: 'Store > Free eBooks' },
  { text: 'Included with your free access', kind: 'label', area: 'Store > Free eBooks' },
  { text: 'Back to store', kind: 'label', area: 'Store > eBook Viewer' },
  { text: "Couldn't load this eBook. It may have been removed.", kind: 'label', area: 'Store > eBook Viewer' },
  { text: 'If the PDF doesn\'t display above, use "Open in new tab".', kind: 'label', area: 'Store > eBook Viewer' },
  { text: 'Free eBooks and resources', kind: 'label', area: 'Dashboard > Store Teaser' },
  { text: "Below the books for purchase, the Store also lists <strong>Free eBooks</strong> - PDF resources you can read without buying anything. Each one shows its cover and description with two buttons: <strong>Read</strong> opens the PDF right in the app (on the Android app it opens in your device's browser instead), and <strong>Open in new tab</strong> hands it to your browser - handy for downloading or printing.", kind: 'html', area: 'Help > Store' },
  { text: 'The list starts collapsed - tap the Free eBooks heading to open or close it.', kind: 'label', area: 'Help > Store' },
];
